# Generated by Django 4.2.6 on 2023-10-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
