# Generated by Django 4.2.6 on 2023-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dead_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='dead_at',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
