# Generated by Django 4.2.6 on 2023-10-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_todo_dead_time_todo_dead_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dead_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
