# Generated by Django 4.2.6 on 2023-10-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_todo_dead_at_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='crtd_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
