# Generated by Django 4.2.6 on 2023-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_todo_crtd_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='crtd_at',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
